on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u namratajha --password-stdin
        
      - name: Docker pull
        run: docker pull ghcr.io/namratajha/only-pkg/nats:latest
        
